version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.1
  - dependency-name: "@commitlint/travis-cli"
    versions:
    - 12.0.1
  - dependency-name: ember-cli-babel
    versions:
    - 7.26.2
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.2
    - 5.6.5
  - dependency-name: ember-source
    versions:
    - 3.25.0
    - 3.25.1
  - dependency-name: babel-plugin-debug-macros
    versions:
    - 0.3.4
