# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

on:
  pull_request:
  push:
    branches:
      master
    tags:
      - '*'

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x' # preferred node version
      - name: yarn install
        run: yarn --frozen-lockfile --install
      - name: lint
        run: yarn lint

  test:
    name: test
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x' # min node version
      - name: yarn install
        run: yarn --frozen-lockfile --install
      - name: test
        run: yarn test

  test-production:
    name: test production build
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x' # min node version
      - name: yarn install
        run: yarn --frozen-lockfile --install
      - name: test
        run: yarn test:production

  test-performance-app:
    name: performance-app
    needs: [lint]
    runs-on: ubuntu-latest

    # run all of the commands below inside the perf test app
    defaults:
      run:
        working-directory: m3-perf-testing-app

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x' # min node version
      - name: yarn install
        run: yarn --frozen-lockfile --install
      - name: test:performance-app
        run: yarn test

  test-node:
    name: "t:${{matrix.node}}"
    needs: [lint, test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [12.x, 14.x, 16.x] # Active and Current LTS
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - name: yarn install
        run: yarn --frozen-lockfile --install
      - name: test
        run: yarn test

  test-ember:
    name: "t:${{matrix.try-scenario}}"
    needs: [lint, test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        try-scenario: [release-channel, release-n-1, ember-lts, ember-lts-n-1, ember-data-packages-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: yarn install
        run: yarn --frozen-lockfile --install
      - name: try ${{matrix.try-scenario}}
        run: yarn run ember try:one ${{matrix.try-scenario}}

  browser-tests:
    needs: [lint]
    runs-on: windows-latest
    name: test-ie
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x' # preferred node version
      - name: yarn install
        run: yarn --frozen-lockfile --install
      - name: test
        env:
          TESTEM_CI_LAUNCHER: IE
          CI: true
        run: yarn test
