# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Nightly

on:
  schedule:
    # minute hour day-of-month month day-of-week
    - cron: '0 14 * * *' # 1400 UTC / 0600 PT
  workflow_dispatch:

jobs:
  test-floating-deps:
    name: 'test (floating dependencies)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x' # min node version
      - name: yarn install
        run: yarn install --no-lockfile
      - name: test
        run: yarn test

  test-canaries:
    name: "t:${{matrix.try-scenario}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        try-scenario: [ember-latest, ember-beta, ember-alpha, ember-data-beta, ember-data-canary]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: yarn install
        run: yarn --frozen-lockfile --install
      - name: try ${{matrix.try-scenario}}
        run: yarn run ember try:one ${{matrix.try-scenario}}
      - name: create issue
        if: failure()
        run: "yarn nyx report-failure --owner hjdivad --repo ember-m3 --run-id ${{github.run_id}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-feature-flags:
    name: feature flags
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x' # min node version
      - name: yarn install
        run: yarn --frozen-lockfile --install
      - name: test:feature-flags
        run: yarn run ember try:one ember-data-canary --- ember test --query enableoptionalfeatures
